### PR TITLE
Upgrade to 2021 edition

### PR DESCRIPTION
**Pull request by obeis**
Signed-off-by: Obei Sideg <obei.sideg@gmail.com>

### Summary of the PR

Upgrade to 2021 edition

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Review by sboeuf — DISMISSED** [review]

**Comment by jiangliu** [comment]
What's the benefits of this upgrading?

**Comment by obeis** [comment]
I think it's better to use latest stable version of rust

**Comment by wllenyj** [comment]
https://doc.rust-lang.org/edition-guide/editions/index.html#editions-do-not-split-the-ecosystem
```
The most important rule for editions is that crates in one edition can interoperate seamlessly with crates compiled in other editions. This ensures that the decision to migrate to a newer edition is a "private one" that the crate can make without affecting others.
```
Does this mean that other crates that depend on this crate will not fail to compile due to the editions issue?

**Review by JonathanWoollett-Light — DISMISSED** [review]

**Comment by stefano-garzarella** [comment]
> https://doc.rust-lang.org/edition-guide/editions/index.html#editions-do-not-split-the-ecosystem
> 
> > The most important rule for editions is that crates in one edition can interoperate seamlessly with crates compiled in
> > other editions. This ensures that the decision to migrate to a newer edition is a "private one" that the crate can make
> > without affecting others.
> 
> Does this mean that other crates that depend on this crate will not fail to compile due to the editions issue?

So it looks like we can update it.

I think this PR fell into the crack, let's try to start again ;-) 

@obeis can you rebase on current main?

**Comment by obeis** [comment]
@stefano-garzarella Done

**Review by sboeuf — APPROVED** [review]

**Review by stefano-garzarella — APPROVED** [review]

**Pull request merged**
