### PR TITLE
New releases: vhost v0.9.0 and vhost-user-backend v0.11.0

### PR DESCRIPTION
**Pull request by stefano-garzarella**
### Summary of the PR

Preparation for a new release for both `vhost` and `vhost-user-backend`

I also run semver-checks:
```
$ cargo semver-checks check-release
     Parsing vhost v0.9.0 (current)
     Parsing vhost v0.8.1 (baseline)
    Checking vhost v0.8.1 -> v0.9.0 (major change)
   Completed [   0.000s] 0 checks; 0 passed, 48 unnecessary
     Parsing vhost-user-backend v0.11.0 (current)
     Parsing vhost-user-backend v0.10.1 (baseline)
    Checking vhost-user-backend v0.10.1 -> v0.11.0 (major change)
   Completed [   0.000s] 0 checks; 0 passed, 48 unnecessary
```

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by stefano-garzarella** [comment]
Marked as draft since we may want to merge others PR before the release, for example:
- https://github.com/rust-vmm/vhost/pull/116
- https://github.com/rust-vmm/vhost/pull/155
- https://github.com/rust-vmm/vhost/pull/190

**Comment by stefano-garzarella** [comment]
@Ablu @aesteve-rh can you check the changelog changes we discussed in https://github.com/rust-vmm/vhost/pull/187#discussion_r1341000272 ?

**Review by Ablu — APPROVED** [review]

**Review by aesteve-rh — APPROVED** [review]
LGTM!

**Review by sboeuf — APPROVED** [review]
:+1:

**Comment by Ablu** [comment]
@stefano-garzarella does anything block dropping the DRAFT status? :thinking:

**Comment by stefano-garzarella** [comment]
> @stefano-garzarella does anything block dropping the DRAFT status? 🤔

I was waiting for #194 that I discovered yesterday after merging #116. (now is merged)
I also pinged old PRs like #88 that we never merged, but maybe we should. Anyway, I don't see any answer yet, so we can postpone it.

The only one I'm thinking of is #190 (that is also breaking IIUC), but we need to wait a `virtio-queue` release first, so if we really need this release soon, we can postpone also that one.

**Comment by Ablu** [comment]
> so if we really need this release soon, we can postpone also that one.

No need to rush. Just tried to get a feeling of where we are.

**Comment by stefano-garzarella** [comment]
@eryugey @jiangliu @sboeuf @slp I marked this ready since I think #88 and #190 will take time, but I'm open to postpone this release to wait them.

**Review by Ablu — APPROVED** [review]

**Comment by rbradford** [comment]
@stefano-garzarella Would be great to get the vm-memory bump (#190) in - vm-memory updates always create a lot of work (in terms of new create release needs.)

**Comment by Ablu** [comment]
This is a bit annoying that we came into this siutation... #190 depends on a bump of vm-memory in vm-virtio. Looks like vm-virtio was misconfigured and did not receive pokes from @dependabot to update the crate. Filed a PR to fix that (https://github.com/rust-vmm/vm-virtio/pull/259).

Now about updating vm-memory: I looked into doing that, but it is not so trivial. Migrating to the new VolatileRead/Write traits is not so straight-forward there. I added a comment on https://github.com/rust-vmm/vm-memory/pull/247#issuecomment-1749363773, trying to figure out a way forward. But  I am not sure if it is solvable with the current API or may require some adapter between the rust-vmm and Rust's standard traits.

All in all, this will probably take some time to settle as no one is actively working on doing the update.

**Comment by Ablu** [comment]
IMHO the last dependency before we can merge this is https://github.com/rust-vmm/vhost/pull/200. Am I missing something?

**Comment by stefano-garzarella** [comment]
> IMHO the last dependency before we can merge this is #200. Am I missing something?

Yep, I think so. I'll rebase it.

**Comment by stefano-garzarella** [comment]
This is now ready. @sboeuf @jiangliu @slp please take a look.

**Review by Ablu — APPROVED** [review]

**Review by sboeuf — APPROVED** [review]

**Review by rbradford — APPROVED** [review]

**Comment by aesteve-rh** [comment]
So, can I try to update `vhost-device` crates to use the new release already? Or is the process automatized?

**Comment by stefano-garzarella** [comment]
> So, can I try to update `vhost-device` crates to use the new release already? Or is the process automatized?

Thank you very much for the help!

dependabot should do the update (I just asked here: https://github.com/rust-vmm/vhost-device/pull/527#issuecomment-1798573162), but if there is any breaking change, we need to update the code.
This should be the case here, but @Ablu already created this: https://github.com/rust-vmm/vhost-device/pull/461 so maybe we just need to update it.

**Pull request merged**
