### PR TITLE
CODEOWNERS: add myself

### PR DESCRIPTION
**Pull request by Ablu**
@stefano-garzarella asked me whether I would be willing to help with reviews here.

While my availability will probably be a lot worse starting with next year, I should still be able to do some reviews or ocassional releases.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- `na` All added/changed functionality has a corresponding unit/integration
  test.
- `na` All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- `na` Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by Ablu** [comment]
Quoting from [the process](https://github.com/rust-vmm/community/blob/main/MAINTAINERS.md#becoming-a-repository-maintainer):

> Irrespective of who created the PR, all existing code owners (as defined in theCODEOWNERS file) must approve the PR before it is merged. In case there are no code owners in the repository, ask [2 gatekeepers](https://github.com/rust-vmm/community/blob/main/MAINTAINERS.md#gatekeepers) to approve the PR for you.

**Review by stefano-garzarella — APPROVED** [review]

**Comment by stefano-garzarella** [comment]
@eryugey @jiangliu @sboeuf @slp gentle ping.

I think Erik can help a lot in this period that you are busy, we have several PRs to merge, and we are a bit stuck.
Thanks ;-)

**Review by sboeuf — APPROVED** [review]
Of course :+1:

**Review by jiangliu — APPROVED** [review]

**Comment by stefano-garzarella** [comment]
@jiangliu we were waiting for a full agreement.

@slp @eryugey please let us know if this is fine with you.

**Comment by eryugey** [comment]
> @jiangliu we were waiting for a full agreement.
> 
> @slp @eryugey please let us know if this is fine with you.

Sorry, I'm late, but I'm fine with it. Thanks!

**Pull request merged**
