### PR TITLE
Cleanups

### PR DESCRIPTION
**Pull request by vireshk**
Few generic reorg and cleanups.

### CODE REVIEW

**Comment by vireshk** [comment]
Any idea why the builds are failing ?

@jiangliu @slp @stefano-garzarella

**Comment by stefano-garzarella** [comment]
@vireshk we were talking about that with @jiangliu just yesterday.

It seems the new `log` version requires rustc >= 1.60, while the CI is using 1.58.1:

```
error: package `log v0.4.19` cannot be built because it requires rustc 1.60.0 or newer, while the currently active rustc version is 1.58.1
```

I don't know whether it is better to set log to a lower version or upgrade rustc in the CI. The latter I don't know how complicated it is, so maybe we could downgrade log?

**Comment by stefano-garzarella** [comment]
@vireshk yep, will be nice to fix them.

Are you working on that?
Otherwise, I can help with that.

**Review by stefano-garzarella — DISMISSED** [review]

**Comment by stefano-garzarella** [comment]
> > I don't know whether it is better to set log to a lower version or upgrade rustc in the CI. The latter I don't know how complicated it is, so maybe we could downgrade log?
> 
> Yeah, I looked at it. There are several clippiy warnings (around usage unsafe blocks withtout comments), which is stopping us to upgrade to a new CI version.
> 
> #167

I pushed some commits in that PR to fix the issues, so maybe we can merge that PR here (or merge in main) and avoid fixing the `log` version here.

**Comment by stefano-garzarella** [comment]
There is an issue in `rust-vmm-ci` that I fixed here: https://github.com/rust-vmm/rust-vmm-ci/pull/129

Anyway, we are increasing the coverage here :-) :
```
Current code coverage (84.00%) deviates by -0.70% from the previous code coverage 83.30%.Current code coverage must be within the range 83.30%..83.80%.Please update the coverage in `coverage_config_x86_64.json`.
```

**Comment by vireshk** [comment]
> ```
> Current code coverage (84.00%) deviates by -0.70% from the previous code coverage 83.30%.Current code coverage must be within the range 83.30%..83.80%.Please update the coverage in `coverage_config_x86_64.json`.
> ```

I couldn't find this in the failure log, where did you get this from ?

**Comment by jiangliu** [comment]
You guys are crazy, I will get overloaded by your progress:)
After all, thanks for your efforts to take care of these!

**Review by jiangliu — APPROVED** [review]

**Comment by stefano-garzarella** [comment]
> > ```
> > Current code coverage (84.00%) deviates by -0.70% from the previous code coverage 83.30%.Current code coverage must be within the range 83.30%..83.80%.Please update the coverage in `coverage_config_x86_64.json`.
> > ```
> 
> I couldn't find this in the failure log, where did you get this from ?

Locally with the fix I sent yesterday here: https://github.com/rust-vmm/rust-vmm-ci/pull/129

**Review by stefano-garzarella — APPROVED** [review]

**Pull request merged**
