### PR TITLE
Use File for slave request fd

### PR DESCRIPTION
**Pull request by jynnantonix**
There is nothing in the vhost-user documentation or spec that says this
must be a socket for fs device requests.  It's not even guaranteed that
it is an fd for a UnixStream.

Change the type to a File and leave it up to the backend to convert it
into a more specialized type if necessary.  Ideally we'd use something
like UniqueFd, which provides close-on-drop functionality but doesn't
make any other assumptions, but since we don't have that File is the
next best thing.

Signed-off-by: Chirantan Ekbote <chirantan@chromium.org>

### CODE REVIEW

**Comment by slp** [comment]
Makes sense, but this will break every consumer of this crate, so we need to be careful about when to merge it.

@jiangliu do you think this should be in before or after 0.1.0 gets published?

**Comment by jiangliu** [comment]
> Makes sense, but this will break every consumer of this crate, so we need to be careful about when to merge it.
> 
> @jiangliu do you think this should be in before or after 0.1.0 gets published?

I have a little preference for releasing v0.1 before merging this MR, so other projects depending on vhost could move on.

**Comment by slp** [comment]
> I have a little preference for releasing v0.1 before merging this MR, so other projects depending on vhost could move on.

Okay, I agree.

**Comment by jiangliu** [comment]
@jynnantonix could please help to rebase the MR?

**Comment by jiangliu** [comment]
After a second thoughts, I'm a little curious what's the usage case for this change?

**Pull request closed without merging**
