### PR TITLE
Draft: vDPA without skip test commit

### PR DESCRIPTION
**Pull request by stefano-garzarella**
Draft PR without commit that skip vdpa tests if the device is not available to check if everything is okay

### CODE REVIEW

**Comment by stefano-garzarella** [comment]
@catalindumitru I think aarch64 image is not building vdpa kernel modules. What we can do?

The #33 contains a commit to skip the vdpa tests in that case, so it's safe and eventually we can leave it that way.

**Comment by catalindumitru** [comment]
Hi @stefano-garzarella, we have previously checked that the device is actually found by adding an assert at the end of one of the tests (in this [commit](https://github.com/rust-vmm/vhost/pull/75/commits/475371f2da95ebafd15e55e54995d6d614e31dd0)). The tests in the Buildkite [build](https://buildkite.com/rust-vmm/vhost-ci/builds/219#4a36e77e-eb64-4168-8a99-44f571434e54) (including the aarch64 ones) seemed to fail because of this assert. We are looking into the issue.

**Comment by andreeaflorescu** [comment]
@stefano-garzarella skipping the tests in case the device is not found might lead to silent failures in the CI. We might want to just have the tests under a feature in case the device is not found locally during development, but in the CI is safer to have it tested.

**Comment by stefano-garzarella** [comment]
@andreeaflorescu yep, make sense.

So, if you and @catalindumitru agree, I'll close this PR, and remove the [commit](https://github.com/rust-vmm/vhost/pull/33/commits/69e76296438196b881ab3dab7928ff5e3644f22a) that skip the test from #33.

The tests are already under `vhost-vdpa` feature, is that okay?

**Comment by andreeaflorescu** [comment]
We first need to identify the reason for the failure :(

Let's wait a bit until we figure out what is going on.

**Comment by lauralt** [comment]
@stefano-garzarella We weren't able to fix the issue for the aarch64 instance, and we need more time. But anyway, it's a problem with our instances, not with the test, so I'm fine as well with skipping the tests for now. Sorry for the late response :(.

**Comment by lauralt** [comment]
Also, looks like if we add `vhost-vdpa` and `vdpa-sim-net` to a 5.11.0 kernel, there won't be any vhost-vdpa-0 device. Any idea why? Is there a problem with this particular kernel version?

**Comment by stefano-garzarella** [comment]
> @stefano-garzarella We weren't able to fix the issue for the aarch64 instance, and we need more time. But anyway, it's a problem with our instances, not with the test, so I'm fine as well with skipping the tests for now. Sorry for the late response :(.

Okay, thanks for the update! I just rebased #33, but CI is failing with a strange behavior (Permission denied removing stuff). How can I restart it?

**Comment by stefano-garzarella** [comment]
> Also, looks like if we add `vhost-vdpa` and `vdpa-sim-net` to a 5.11.0 kernel, there won't be any vhost-vdpa-0 device. Any idea why? Is there a problem with this particular kernel version?

This is strange, for 5.11 should be enough, but I just remembered that starting from 5.12 a new management API is added to handle vDPA sim devices: https://github.com/torvalds/linux/commit/a3c06ae158dd6fa8336157c31d9234689d068d02

So you need to use `vdpa` tool from [iproute2](https://git.kernel.org/pub/scm/network/iproute2)/iproute2.git to add a new device instance:
```bash
sudo modprobe vhost-vdpa
sudo modprobe vdpa-sim-net
./vdpa dev add mgmtdev vdpasim_net name dev1
```

Then you can check in this way:
```
$ ./vdpa dev list     
dev1: type network mgmtdev vdpasim_net vendor_id 0 max_vqs 2 max_vq_size 256
```

**Comment by lauralt** [comment]
> > @stefano-garzarella We weren't able to fix the issue for the aarch64 instance, and we need more time. But anyway, it's a problem with our instances, not with the test, so I'm fine as well with skipping the tests for now. Sorry for the late response :(.
> 
> Okay, thanks for the update! I just rebased #33, but CI is failing with a strange behavior (Permission denied removing stuff). How can I restart it?

Fixed it.

**Pull request closed without merging**
