### PR TITLE
Inflight io: Define queue regions for split and packed virtqueues

### PR DESCRIPTION
**Pull request by harshanavkis**
These set of commits introduce the queue region and descriptor state structures needed to manage inflight I/O tracking.

### CODE REVIEW

**Comment by jiangliu** [comment]
Could you please help to add Signed-off-By to commit message and fix the warnings?

**Comment by harshanavkis** [comment]
@jiangliu I fixed most of the errors and your comments.However, the coverage still fails. Do you have any idea on how to fix this? I haven't included any tests as there are no useful interfaces on the structs for now.

**Comment by jiangliu** [comment]
> @jiangliu I fixed most of the errors and your comments.However, the coverage still fails. Do you have any idea on how to fix this? I haven't included any tests as there are no useful interfaces on the structs for now.

it's ok to decrease coverage for this case. It a waste to add nonsense test cases for coverage:)

**Comment by harshanavkis** [comment]
Yes, makes sense. Thanks.

**Comment by stefano-garzarella** [comment]
@harshanavkis I think you can modify `coverage_config_x86_64.json` in this PR reducing the score of 0.8 to avoid the coverage failure, something like this:

```patch
--- a/coverage_config_x86_64.json
+++ b/coverage_config_x86_64.json
@@ -1 +1 @@
-{"coverage_score": 83.6, "exclude_path": "src/vhost_kern/", "crate_features": "vhost-user-master,vhost-user-slave"}
+{"coverage_score": 82.8, "exclude_path": "src/vhost_kern/", "crate_features": "vhost-user-master,vhost-user-slave"}**
```

**Review by stefano-garzarella — APPROVED** [review]

**Review by jiangliu — APPROVED** [review]

**Review by slp — APPROVED** [review]

**Pull request merged**
