### PR TITLE
Add custom pipeline yaml for wider clippy coverage

### LINKED ISSUE #25: Check non-default feature code and tests in vhost-ci/clippy-x86
The current `clippy-x86` builder in vhost-ci doesn't cover code for non-default features (e.g. `vhost-kern`, `vhost-user`, etc). So, we have some clippy errors there now, which will be fixed by #23.
To improve code quality, it would be nice if we can pass more flags in clippy there like `clippy --all-targets --all-features`.

### PR DESCRIPTION
**Pull request by keiichiw**
Fixes #25.

### CODE REVIEW

**Comment by keiichiw** [comment]
@andreeaflorescu, can I ask you to review this?
It seems that the new check wasn't triggered, but I'm not sure if it's expected. How can we check that my YAML is correct?

**Comment by andreeaflorescu** [comment]
@keiichiw we need to enable the pipeline in Buildkite as well. I would suggest to first review the PR, and then update Buildkite to pick up the changes.

**Comment by keiichiw** [comment]
@andreeaflorescu It makes sense. Then, could you review this PR? Also, who do you know I should ask to update Buildkite?

**Comment by jiangliu** [comment]
Should we also add steps for release buildings for gnu and musl?

**Comment by keiichiw** [comment]
It seems that vm-memory pipelines tests gnu and musl with `backend-mmap`, whose behavior may change depending on libc implementation. However, I don't think the vhost crate uses libc in such a way.
Also, the vhost uses vm-memory with `backend-mmap` feature in dev-dependencies, but release building shouldn't use it. So, I feel we don't have to add such steps. What do you think?

**Review by jiangliu — APPROVED** [review]

**Comment by jiangliu** [comment]
@slp @sboeuf Could you please help to review this MR?

**Review by sboeuf — COMMENTED** [review]
This change LGTM but could you get rid of the 3 merge commits by doing a simple rebase?

**Comment by keiichiw** [comment]
I just rebased the commit.

**Review by sboeuf — APPROVED** [review]
Thanks @keiichiw

**Review by jiangliu — APPROVED** [review]

**Comment by jiangliu** [comment]
> @keiichiw we need to enable the pipeline in Buildkite as well. I would suggest to first review the PR, and then update Buildkite to pick up the changes.

@andreeaflorescu Any doc/manual to enable Buildkite for vhost?

**Comment by andreeaflorescu** [comment]
I added it: https://buildkite.com/rust-vmm/vhost-ci/builds/85#2247d02c-2192-4ca9-a28c-a180c70acfa3

We don't have documentation for that yet :(

**Pull request merged**
