### PR TITLE
Prepare for release v0.2.0

### PR DESCRIPTION
**Pull request by slp**
Update version in Cargo.toml and add info about v0.2.0 to CHANGELOG.md

Signed-off-by: Sergio Lopez <slp@redhat.com>

### CODE REVIEW

**Comment by slp** [comment]
This would be a very small minor release with just a couple of changes, but #74 is a blocker for [virtiofsd-rs](https://gitlab.com/virtio-fs/virtiofsd-rs), so it'd be great if we can do this.

**Comment by jiangliu** [comment]
Could we get the vdpa work into v0.2? I feel the vdpa work is near for merging:)

**Comment by slp** [comment]
> Could we get the vdpa work into v0.2? I feel the vdpa work is near for merging:)

Oh, yes, that's true. Let's wait a bit then.

**Comment by stefano-garzarella** [comment]
> Could we get the vdpa work into v0.2? I feel the vdpa work is near for merging:)

That would be cool!
We still have some issues with the CI (see #82) but we can merge #33 with the patch that skips the tests if there isn't the device, and when the CI will be ready, we can revert it.

@andreeaflorescu @slp @jiangliu what do you think?

**Comment by jiangliu** [comment]
> > Could we get the vdpa work into v0.2? I feel the vdpa work is near for merging:)
> 
> That would be cool!
> We still have some issues with the CI (see #82) but we can merge #33 with the patch that skips the tests if there isn't the device, and when the CI will be ready, we can revert it.
> 
> @andreeaflorescu @slp @jiangliu what do you think?

sound like a plan:)

**Comment by jynnantonix** [comment]
Would it be possible to also get #49 into the 0.2 release?

**Comment by jiangliu** [comment]
> Would it be possible to also get #49 into the 0.2 release?

Yes, that's the only pending MR for v0.2. But I'm a little curious about the usage cases. Could you please help elaborate more about the usage cases?

**Comment by slp** [comment]
I'm sorry to keep insisting, but v0.2.0 is a blocker for virtiofsd-rs. Can we agree on a deadline for the release?

**Comment by sboeuf** [comment]
I'm in favor of releasing v0.2.0 right now. Releases are cheap, we can do another one for the remaining items.

**Comment by stefano-garzarella** [comment]
I'm in favor too to release ASAP.
Also `vhost-user-backed` CI is failing because of this crate.

**Review by jiangliu — APPROVED** [review]

**Review by stefano-garzarella — APPROVED** [review]

**Pull request merged**
