### PR TITLE
vhost v0.12.1 and vhost-user-backend v0.16.1 release

### PR DESCRIPTION
**Pull request by stefano-garzarella**
### Summary of the PR

Remove the gpu-socket feature just introduced, since it doesn't work well with cargo feature unification.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by stefano-garzarella** [comment]
After these releases, I'm undecided whether to yank the previous two. I don't expect any backend is using gpu_socket, so I'm not sure if it's necessary or not.

Opinions?

**Comment by TimePrinciple** [comment]
> After these releases, I'm undecided whether to yank the previous two. I don't expect any backend is using gpu_socket, so I'm not sure if it's necessary or not.
> 
> Opinions?

IMHO if that's a serious problem, we should yank it to let downstream notice that change and fix it accordingly. I'm not an expert on that so I can only say it's up to you to decide how serious it is :)

**Comment by stefano-garzarella** [comment]
> > After these releases, I'm undecided whether to yank the previous two. I don't expect any backend is using gpu_socket, so I'm not sure if it's necessary or not.
> > Opinions?
> 
> IMHO if that's a serious problem, we should yank it to let downstream notice that change and fix it accordingly. I'm not an expert on that so I can only say it's up to you to decide how serious it is :)

Yeah, and maybe also to avoid future backends using those versions. I thought it can affect just gpu backends, but we saw in vhost-device that the feature unification affects other, so yep, I'll yank it.

**Comment by Ablu** [comment]
LGTM! But we should also document in the changelog why we yanked versions IMHO. But that can happen separately of course.

**Review by Ablu — APPROVED** [review]

**Review by rbradford — APPROVED** [review]

**Comment by stefano-garzarella** [comment]
> LGTM! But we should also document in the changelog why we yanked versions IMHO. But that can happen separately of course.

Yep, good point. I'll open another PR with that changes and I'll yank them only after that PR will be merged!

**Pull request merged**
