### PR TITLE
Fix clippy erros and warnings

### PR DESCRIPTION
**Pull request by keiichiw**
Make `cargo clippy --all-features --all-targets` pass.

### CODE REVIEW

**Comment by jiangliu** [comment]
Thanks for help to improve code quality:)
There's a pending PR #19 , which touches/removes most of the issues solved by this PR.
So could we merge the #19 first?

**Comment by keiichiw** [comment]
That sounds good to me as long as #19 will be merged soonish. I'll update (or close) this CL once #19 is merged.

**Comment by keiichiw** [comment]
I just rebased my commit on #19 and made sure clippy passed. Please take a look!

**Review by jiangliu — APPROVED** [review]

**Comment by keiichiw** [comment]
Hi, can anyone give one more approval for this PR?

**Review by andreeaflorescu — APPROVED** [review]

**Pull request merged**
