### PR TITLE
Prepare for publishing to crates.io

### PR DESCRIPTION
**Pull request by jiangliu**
This big PR polishes the vhost design and implementation, preparing for publishing to crates.io.
The main changes are:
1) Abstract interface traits into two category: one with interior mutability, and another without interior mutability. Advanced drivers may use interface traits with interior mutability to better improve performance by using multi-threading.
2) Fix several bugs.
3) Improve documentation
4) Add more unit test cases to improve code coverage.

### CODE REVIEW

**Comment by slp** [comment]
I've started looking at this PR. So far LGTM, but since it's quite large, I'd like to take a second look next week (Monday, most likely).

**Review by sboeuf — COMMENTED** [review]
The content of the PR looks good to me.
I think it'd be nice to fix the few typos that you have in your commit messages. Also, please try to provide a commit body for each of your commits.
Also, it's worth noting that I've validated Cloud Hypervisor is still working correctly with this PR (a few changes are needed). And I appreciated the introduction of immutable traits since it reduces the locking complexity.

**Comment by jiangliu** [comment]
> The content of the PR looks good to me.
> I think it'd be nice to fix the few typos that you have in your commit messages. Also, please try to provide a commit body for each of your commits.
> Also, it's worth noting that I've validated Cloud Hypervisor is still working correctly with this PR (a few changes are needed). And I appreciated the introduction of immutable traits since it reduces the locking complexity.

I have updated commit log messages, forgive my poor english:(

**Review by sboeuf — APPROVED** [review]
LGTM :)

**Review by slp — APPROVED** [review]
Reviewed and tested with `vhost-user-backend`+`virtiofsd` (needs a minor change to deal with the interior mutability change, as expected). LGTM. 👍

**Pull request merged**
