### PR TITLE
Move all crates to workspace root

### PR DESCRIPTION
**Pull request by epilys**
### Summary of the PR

Having all the workspace crates under the crates/ directory is unnecessary. Rust documentation itself recommends all crates to be in the root directory:

https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html#creating-the-second-package-in-the-workspace

I paste the text content here, in case the online page ever changes or becomes unavailable:

    ## Creating the Second Package in the Workspace

    Next, let’s create another member package in the workspace and call it add_one. Change the top-level Cargo.toml to specify the add_one path in the members list:

    Filename: Cargo.toml

    [workspace]

    members = [
        "adder",
        "add_one",
    ]

    Then generate a new library crate named add_one:

    $ cargo new add_one --lib
         Created library `add_one` package

    Your add directory should now have these directories and files:

    ├── Cargo.lock
    ├── Cargo.toml
    ├── add_one
    │   ├── Cargo.toml
    │   └── src
    │       └── lib.rs
    ├── adder
    │   ├── Cargo.toml
    │   └── src
    │       └── main.rs
    └── target

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by sboeuf** [comment]
That sounds good to me. Getting rid of the `crates` indirection directory is a nice simplification.

**Review by stefano-garzarella — APPROVED** [review]

**Comment by stefano-garzarella** [comment]
As I reported in the [discussion for rust-vmm/vhost-device changes](https://github.com/rust-vmm/vhost-device/pull/455#issuecomment-1733990849), my (very weak) preference to keep `crates/` is just to make it straightforward to figure out which crates are in the workspace and divide them from, for example, git submodules present in the root (i.e. `rust-vmm-ci`).

That said, we only have 2 crates here, and I think it's really unnecessary indirection, so it's fine with me if we all agree.

I would say have a wide consensus before making this change.

@eryugey @jiangliu @sboeuf @slp  can you approve this PR if you agree on this change (or make a comment if not of course)?

**Review by sboeuf — DISMISSED** [review]

**Comment by epilys** [comment]
Rebased against `main`.

**Review by stefano-garzarella — DISMISSED** [review]

**Comment by epilys** [comment]
Ping 

@eryugey

@jiangliu

@slp

@sboeuf

**Review by Ablu — DISMISSED** [review]

**Comment by stefano-garzarella** [comment]
@epilys now we have 2 approvals, please can you rebase it?

**Review by stefano-garzarella — APPROVED** [review]

**Review by Ablu — APPROVED** [review]

**Pull request merged**
