### PR TITLE
CHANGELOGs: uniform and fix some inconsistencies

### PR DESCRIPTION
**Pull request by stefano-garzarella**
### Summary of the PR

Every time I do a release I notice this difference between
changelogs in this workspace, so let's try to uniform them by using
the form used in vhost-user-backend: without square brackets in the
title of the release and the `v` as prefix (v0.0.0).

Also fixed some difference in how we link PRs, let's follow the
most used way: [[#000]](url)

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by stefano-garzarella** [comment]
I based this on top of #273 so we don't need to fix the conflicts. So marking as draft till we have it merged.

**Comment by TimePrinciple** [comment]
Maybe we could use mdformat that kind of thing to take care of formatting on CHANGELOG.md, then people won't easily break consistency 🤔

**Comment by stefano-garzarella** [comment]
> Maybe we could use mdformat that kind of thing to take care of formatting on CHANGELOG.md, then people won't easily break consistency 🤔

Do you mean in the CI?

**Comment by TimePrinciple** [comment]
> > Maybe we could use mdformat that kind of thing to take care of formatting on CHANGELOG.md, then people won't easily break consistency 🤔
> 
> Do you mean in the CI?

Yes, we can put some checks (run some formatters) in our CI :)

**Pull request merged**
